### ISSUE TITLE
Build docs table for metadata package

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#253] opened 2018-08-08 10:50 UTC
@Bjwebb to output a table for the Metadata / package schema here:

![360Giving-Data-Standard-documentation (2)](https://user-images.githubusercontent.com/1209944/113153379-f0bcfb80-922e-11eb-9391-f4e079b95419.png)

https://github.com/ThreeSixtyGiving/standard/blob/2021-package-metadata/documentation/reference.md#meta-sheet

@KDuerden this will be generated directly from the schema - so any mismatches with https://docs.google.com/document/d/1JcPA84zBwjN48k01gITkmAgSN24BJnLLyEc6Rh_eutc/edit#heading=h.ksut49wrb8nk would have to be remedied through schema edits (but I think all is fine)

**Comment by Bjwebb** [comment] 2021-03-31 14:52
@stevieflow How does this look?

![Screenshot from 2021-03-31 15-45-39](https://user-images.githubusercontent.com/634/113163556-2fa37f00-9238-11eb-8fff-df599dbf0ad8.png)

**Comment by KDuerden** [comment] 2021-03-31 14:54
Yes that looks great.

**Comment by stevieflow** [comment] 2021-03-31 14:55
Perfect, thanks @Bjwebb

**Comment by Bjwebb** [comment] 2021-04-01 09:15
@KDuerden This is automatic. The problem is that there's a "oneOf" in the schema (it can be date-time, or a date matching the given regex), so it dosen't know which to display. "Award Date" in the grants table has the same problem.

**Comment by Bjwebb** [comment] 2021-04-01 09:34
Table is now at https://standard.threesixtygiving.org/en/2021-package-metadata/reference/#meta-sheet

**Comment by stevieflow** [comment] 2021-04-01 10:01
Thanks @Bjwebb 

With this and https://github.com/ThreeSixtyGiving/standard/issues/293 also committed - could you take a look @KDuerden , and then schedule the review (ideally on the PR) with @drkane ?

**Comment by Bjwebb** [comment] 2021-04-01 10:14
Just realised we don't have a PR for the correct branch yet, so I've added that https://github.com/ThreeSixtyGiving/standard/pull/295

**Comment by mrshll1001** [comment] 2023-07-25 15:48
@Bjwebb I'm closing this as completed by #295 please re-open if necessary!

**Closed by mrshll1001** 2023-07-25 15:48 UTC
Labels: metadata
