### ISSUE TITLE
Leading zeros in organisational identifiers 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/standard#222] opened 2017-11-08 17:09 UTC
We got a question about leading zerosin organisational identifiers from Trafford Council, and I realised there is no information about it in the documentation. What is the status on leading zero and can we add it to the documentation?

**Comment by BobHarper1** [comment] 2017-11-08 17:21
I think we did have something previously. I think it went with the review of that page. I found this https://github.com/ThreeSixtyGiving/standard/compare/d25b355e4fd368751a4f6888a13f210dd99529ea...381badc5ca94eb45de8cf284f0a570ac66bc02d5#diff-cf0686ab8522061b4a04e2c123d33165L112 which was added then removed between two close commits. 

I think it needs more advice than simply 'use the leading zero' as people are often caught out by software that removes it without their realisation.

**Comment by stevieflow** [comment] 2017-11-08 20:06
To be clear though - this is about 

- company numbers that have a leading zero and are published in a spreadsheet format in the column ''Recipient Org:Company Number'' ?

-- The issue is that for some, the leading xero "disappears", which is (we think) due to MS Excel making assumptions (does this happen in other spreadsheet software?).

- This is not the same as ``Recipient Org:Identifier`` - although for some publishers there might be formula to pull in the value and add a prefix 

In turn, we think this is a documentation issue, but more _implementation_ guidance rather than core via the description of this field in the schema:

> Registered UK company number, if applicable.

As @BobHarper1 indicated, some guidance was included , but removed through discussion.  And  - the issue is not as straightforward or generic

@morchickit agree?  @K_Duerden also agree?

Further - we can't consider schema validation on this, as a) it would render lots of data invalid b) we're heading to a UK-centric implementation issue

**Comment by stevieflow** [comment] 2017-11-08 20:07
(sorry, closed by mistake)

**Comment by KDuerden** [comment] 2017-11-09 09:34
Edafe created this guidance, in response to publisher questions on this. This page was orphaned during our recent update:

https://www.threesixtygiving.org/supportobsolete__trashed/guidance/do-i-need-the-leading-0-in-company-numbers/

**Comment by BobHarper1** [comment] 2017-11-09 15:03
That's great, I think we could work that into the documentation keenly enough.

**Comment by KDuerden** [comment] 2017-11-09 16:31
Practically in supporting publishers I've tended to take a pragmatic approach and focus efforts on reinstating missing 0 when creating the Org IDs (which can be easily included as part of formulas to add the prefix), but not getting to hung up on the Recipient Org:Company Number column, because that hard work can be easily undone in the moves between Excel vs CSV.

**Comment by BobHarper1** [comment] 2017-11-16 17:13
Adding to this issue - because of a recently discovered quirk with respect to saving files from OpenRefine which can cause company and charity numbers to become 12345678.0 (therefore potentially  making identifiers wrong and breaking links in GrantNav)

The solution is the same however: format as text, not number.

So I think the approach we take should also cover Recipient Org:Charity Number as well.

**Comment by stevieflow** [comment] 2017-11-16 21:54
>  saving files from OpenRefine 

I think it's only when you export as .xlsx though - not .csv?

**Comment by BobHarper1** [comment] 2017-11-17 09:58
Just tested this to make sure (by exporting .xlsx and .csv from Refine and then running through COVE) - yes that's correct, xlsx (and presumably xls) have that effect. 

So it's not only saving from Excel to CSV, it's also OpenRefine to Excel.

**Comment by morchickit** [comment] 2017-12-07 11:16
Ok, so should we then update @BobHarper1  on the website (where Edafe's doc is) and maybe put it somewhere more prominent? @KDuerden is that ok?

**Comment by KDuerden** [comment] 2017-12-07 12:02
Linking from the Org Identifier section in References docs would be good. 
In terms of location, it seems to fit best either after the 'Additional 360Giving fields for charity and company number' section. Or maybe in the top part of http://standard.threesixtygiving.org/en/latest/identifiers/#organisation-identifier, under the 'For example' about Charity numbers?

@morchickit we need to at least sort the location in wordpress to tidy up the url.

**Comment by BobHarper1** [comment] 2017-12-08 10:32
@KDuerden probably a hint under 'For example' would be best - not all will necessarily use the additional fields but the org-id is a required field

**Comment by KDuerden** [comment] 2017-12-08 10:36
Sounds good. I've cleaned up url to the page: https://www.threesixtygiving.org/support/company-numbers/

**Comment by morchickit** [comment] 2017-12-08 10:45
Great, Bob, I can add a link through the documentation!

**Comment by BobHarper1** [comment] 2017-12-08 10:55
Do we want to review the text on that page or happy with it as it is?

It's simple stuff, but might be worth adding a link to how to change the column format in Excel:
> You can fix this in Excel by formatting the column as text.
to
> You can fix this in Excel by [formatting the column as text](https://support.microsoft.com/en-gb/help/181298/how-to-convert-text-to-numbers-in-excel)

**Comment by BobHarper1** [comment] 2017-12-08 11:15
Here we are now http://standard.threesixtygiving.org/en/222-leading-zeros/identifiers/#organisation-identifier

**Comment by KDuerden** [comment] 2017-12-22 11:11
Bit more wordy, but I think it is worth spelling out the issue so people know why to care. Suggested edit:

UK company numbers are a unique combination of eight numbers but in some cases it includes letters. The majority of company numbers for companies registered in England and Wales start with a leading zero. 
Publishers should be aware of the problems that missing leading zeros in UK company numbers present when creating identifiers. Learn more about how to avoid this pitfall.

**Comment by BobHarper1** [comment] 2017-12-22 11:36
@KDuerden I think the changes I've made below is a bit more precise?

UK company numbers are a unique combination of eight ~~numbers~~ digits ~~but in some cases it includes letters~~, which in some cases include letters as well as numbers. The majority of company numbers for companies registered in England and Wales start with a **leading zero**.

Publishers should be aware of the problems that missing leading zeros in UK company numbers present when creating identifiers. Learn more about how to avoid this pitfall.

**Comment by KDuerden** [comment] 2017-12-22 11:37
Perfect. Happy to go ahead with this.

**Closed** 2017-12-22 11:50 UTC
Labels: Documentation, question
