### ISSUE TITLE
Flagging that a grant is to be regranted

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#176] opened 2017-04-19 11:48 UTC
**Issue**

a number of grants published are intended for redistribution (in the form of subsequent grants) to other organisations.  If all these grants are published with the 360Giving standard there is a risk of "double counting".  

Example record: http://grantnav.threesixtygiving.org/grant/360G-blf-0030116147

**User need**

Publishers need a method to flag that any grant is for redistribution
Data consumers may wish to exclude such grants, or treat them differently in their application - they need a method to identify these records

**Scope creep**

There is a potential for any work around this to get into the realms of "traceability" and relating grant together.  This proposal looks at provision of a simple flag

**Draft proposal**

Add a new field to the standard for a Boolean flag "Regranting"
Could be similar to ``From an open call?`` field (although this is a string)

**Next steps**

Consider the scope of this
Consult with relevant publishers
What impact does this have on publishers
How best to implement

**Comment by timgdavies** [comment] 2017-04-19 13:24
This is an interesting issue. Some quick thoughts: 

How would the business logic work here to avoid double counting?

E.g. If BLF flag that ```"regranting": true``` for ```360G-blf-0030116147```, but the receipient, Big Local Trust, are not publishing 360Giving data - should I count the value of 360G-blf-0030116147? 

Surely it would be better to flag any grants which are made out of upstream grants, in terms of knowing that care should be taken about whether to count these or not. Ideally you would at least need to know the upstream source - to be able to check if they are a publisher, and whether their data should be excluded or not. 

I can image in the research case, that a researcher should know to review certain organisations funding (e.g. BLF endowments) to avoid double-counting, so the issue is more for interfaces that are presenting aggregates. In these cases:

* If BLF gave £1m to Big Local Trust, and Big Local Trust distributed that £1m:
  * It is true that £2m worth of grants have been made, and are captured in the standard;
  * It is not true that £2m of funding has been put into the social economy

However, I'm not sure the question of 'How much has been put into the social economy?' can be answered from a simple interface in the open world of grantmaking... 

On an aside: an alternative approach here would be to add re-granting information to the 'GrantProgramme' object, such that a GrantProgramme indicates it's funding source.

**Comment by timgdavies** [comment] 2017-05-11 07:23
Tagging @ekoner

From discussion of questions from Manchester, I think declaring the 'funding source' of either an individual grant, or a grant programme, on the downstream grant, is the best way to handle this.

**Comment by Julianlstar** [comment] 2017-05-11 23:42
There are specific and perhaps unique circumstances that need to be worked out with regard to the question around double counting grants. With the concern being derived from overstating the money that flows into a particular area which may create unintended consequences. I think the solution in this case may be dealt with by thinking of a grant as a monetary flow with spatial characteristics.

A central government grant to a local authority would be described as a grant of £X coming from a funding organisation that has a particular location. The recipient organisation will also have a geographical location. Both of these spatial characteristics are accommodated in schema. With regranting the local authority is now the funder with a specific location and the recipient would also potentially have a location.

EG.
GB-GOV12 (London) → 360G-GB-GOV12-123456 (£1M) → GB-LAE-MAN (Manchester) → 360G-GB-LAE-MAN-123456 (£1M) → GB-CHC-4356673 (Manchester)

So the first grant is a flow from London to Manchester to GB-LAE-MAN, whereas the second grant is a flow that is internal to Manchester from GB-LAE-MAN. Discounting the spatial characteristics of the flow it would look like there is £2M of grant dispersed in Manchester whereas this is not the case when you account for them. As I said I think this might be unique to LAs as they have a defined area of operation.

**Comment by stevieflow** [comment] 2017-09-07 11:05
@morchickit will move / host this discussion on the forum

**Comment by morchickit** [comment] 2017-11-21 14:02
Moved to the forum. Closing for now! https://forum.threesixtygiving.org/t/how-to-deal-with-redistribution-of-a-grant-in-the-standard-aka-regranting/106

**Closed by morchickit** 2017-11-21 14:02 UTC
Labels: Forum
